name: Publish Application

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish-window:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Configure Git to use HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://github.com/".insteadOf "git@github.com:"
        shell: bash # 或 pwsh，Windows 也支持 git config

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Publish
        run: pnpm run publish
        env:
          AMY_PUBLISH_USERNAME: ${{ secrets.AMY_PUBLISH_USERNAME }}
          AMY_PUBLISH_PASSWORD: ${{ secrets.AMY_PUBLISH_PASSWORD }}
          ALI_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
          ALI_ACCESS_KEY_SECRET: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
